### ISSUE TITLE
Instrument for phet-io

### ISSUE THREAD

**Issue by zepumph** [phetsims/chains#6]
This is mainly to support @jonathanolson and @mattpen in their chipper 2.0 work. I don't think it will take long to do, and will make it so that they can test phet-io builds.

**Comment by zepumph** [comment]
@jonathanolson it should be good to go now. I ran all of the wrappers from the index and things look good. In instance proxies you can set the texts and fire the resetAllButton. Let me know if you want anything else.

**Comment by jonathanolson** [comment]
This has been super helpful, thanks!
