### ISSUE TITLE
branch: ios-i18n

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chains#7]
@mattpen made the most recent commit, assign to someone else if you know who created this branch.

This was identified by `print-branches.sh`. FYI, all non-release branches are supposed to have an associated GitHub issue. Title is of the form "branch: {{branchName}}}". The description should include: the purpose of the branch, expected lifetime of the branch, references to any related issues.

**Comment by mattpen** [comment]
This is to test changes for rosetta:mobile-app branch, see phetsims/rosetta#179.

**Comment by jbphet** [comment]
@mattpen - Can this branch be deleted and the issue closed?

**Comment by jbphet** [comment]
@mattpen - I was going through the list and deleting every branch that GitHub listed as "stale", and I ended up hitting this one.  So, the branch is now gone and unless you need it back this issue can be closed.  If you _do_ need it back, assign it to me and I'll figure out how to restore it.

**Comment by mattpen** [comment]
No, we decided to take a much different path and this branch is not needed
